CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar UNIQUE NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "user_profiles" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "dob" date,
  "gender" varchar,
  "phone_number" varchar,
  "photo_url" varchar,
  "user_id" bigint UNIQUE NOT NULL,
  "default_address_id" bigint UNIQUE,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "wallets" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "balance" int NOT NULL,
  "pin" varchar NOT NULL,
  "user_id" bigint NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "wallet_histories" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" varchar NOT NULL,
  "reference" varchar NOT NULL,
  "date" timestamp NOT NULL,
  "amount" float NOT NULL,
  "wallet_id" bigint NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "sealabs_pays" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "card_number" varchar UNIQUE NOT NULL,
  "active_date" date NOT NULL,
  "card_name" varchar NOT NULL,
  "user_id" bigint NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "user_addresses" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "phone_number" varchar NOT NULL,
  "street" varchar NOT NULL,
  "user_id" bigint NOT NULL,
  "province_id" bigint NOT NULL,
  "city_id" bigint NOT NULL,
  "district_id" bigint NOT NULL,
  "subdistrict_id" bigint NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "provinces" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "cities" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "province_id" bigint NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "districts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "city_id" bigint NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "subdistricts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "postal_code" int UNIQUE NOT NULL,
  "district_id" bigint NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "shops" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "rating" float NOT NULL,
  "joined_date" date NOT NULL DEFAULT (now()),
  "user_id" bigint NOT NULL,
  "address_id" bigint NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "shop_categories" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "shop_id" bigint NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "shop_category_products" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "shop_category_id" bigint NOT NULL,
  "product_id" bigint NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "shop_guests" (
  "uuid" uuid PRIMARY KEY,
  "shop_id" bigint NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "couriers" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar NOT NULL,
  "name" varchar NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "courier_services" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar NOT NULL,
  "name" varchar NOT NULL,
  "courier_id" bigint NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "shop_couriers" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "shop_id" bigint NOT NULL,
  "courier_service_id" bigint NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "products" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar NOT NULL,
  "name" varchar NOT NULL,
  "description" varchar NOT NULL,
  "view" int NOT NULL,
  "is_hazardous" boolean NOT NULL,
  "weight" float NOT NULL,
  "length" float NOT NULL,
  "width" float NOT NULL,
  "height" float NOT NULL,
  "packaged_size" float NOT NULL,
  "is_new" boolean NOT NULL,
  "is_active" boolean NOT NULL,
  "rating" float NOT NULL,
  "shop_id" bigint NOT NULL,
  "category_id" bigint NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "product_couriers" (
  "id" bigint PRIMARY KEY NOT NULL,
  "product_id" bigint NOT NULL,
  "courier_service_id" bigint NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "product_bulk_prices" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "min_quantity" int NOT NULL,
  "max_quantity" int NOT NULL,
  "price" float NOT NULL,
  "product_id" bigint NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "product_medias" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "url" varchar NOT NULL,
  "product_id" bigint NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "variant_groups" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "product_id" bigint NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "variants" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "value" varchar NOT NULL,
  "media_url" varchar,
  "group_id" bigint NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "product_variants" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sku_id" bigint NOT NULL,
  "variant" bigint NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "skus" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sku" varchar UNIQUE NOT NULL,
  "price" float NOT NULL,
  "stock" int NOT NULL,
  "product_id" bigint NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "transactions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "price" float NOT NULL,
  "total_price" float NOT NULL,
  "quantity" int NOT NULL,
  "note" varchar,
  "invoice_id" bigint NOT NULL,
  "address_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "sku_id" bigint NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "transaction_reviews" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "description" varchar NOT NULL,
  "rating" int NOT NULL,
  "review_date" timestamp NOT NULL,
  "transactions_id" bigint NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "review_medias" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "url" varchar NOT NULL,
  "review_id" bigint NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "invoice_per_shops" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar NOT NULL,
  "subtotal" float NOT NULL,
  "total" float NOT NULL,
  "shipping_cost" float NOT NULL,
  "tracking_number" bigint NOT NULL,
  "promotion_amount" float,
  "promotion_type" varchar,
  "voucher_amount" float,
  "voucher_type" varchar,
  "status" varchar NOT NULL,
  "promotion_id" bigint,
  "shop_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "voucher_id" bigint,
  "invoice_id" bigint NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "invoices" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar NOT NULL,
  "total" float NOT NULL,
  "subtotal" float NOT NULL,
  "voucher_amount" float,
  "voucher_type" varchar,
  "user_id" bigint NOT NULL,
  "voucher_id" bigint,
  "payment_method_id" bigint NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "invoice_status" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "status" varchar NOT NULL,
  "status_date" timestamp NOT NULL,
  "invoice_per_shop_id" bigint NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "shop_vouchers" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "code" varchar NOT NULL,
  "amount" float NOT NULL,
  "type" varchar NOT NULL,
  "is_hidden" boolean NOT NULL,
  "description" varchar NOT NULL,
  "minimum_spend" float NOT NULL,
  "expired_at" timestamp NOT NULL,
  "shop_id" bigint NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "marketplace_vouchers" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "code" varchar NOT NULL,
  "amount" float NOT NULL,
  "type" varchar NOT NULL,
  "is_hidden" boolean NOT NULL,
  "description" varchar NOT NULL,
  "minimum_spend" float NOT NULL,
  "expired_at" timestamp NOT NULL,
  "category_id" bigint,
  "payment_method_id" bigint,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "user_vouchers" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "is_used" boolean NOT NULL,
  "expired_at" timestamp NOT NULL,
  "shop_voucher_id" bigint,
  "marketplace_voucher_id" bigint,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "payment_methods" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "categories" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "image_url" varchar NOT NULL,
  "parent_id" bigint,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "cart_items" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "quantity" int NOT NULL,
  "notes" varchar,
  "user_id" bigint NOT NULL,
  "sku_id" bigint UNIQUE NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "wishlist_items" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "product_id" bigint UNIQUE NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "promotions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "start_period" date NOT NULL,
  "end_period" date NOT NULL,
  "shop_id" bigint NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "promotion_products" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" varchar NOT NULL,
  "amount" float NOT NULL,
  "stock" int,
  "purchase_limit" int,
  "sku_id" bigint NOT NULL,
  "promotion_id" bigint NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "refund_requests" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "request_date" timestamp NOT NULL,
  "status" varchar NOT NULL,
  "transaction_id" bigint NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "refund_chats" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "message" varchar NOT NULL,
  "sender_id" bigint NOT NULL,
  "request_id" bigint NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "marketplace_banner" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "media_url" varchar NOT NULL,
  "start_datte" timestamp NOT NULL,
  "end_date" timestamp NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE UNIQUE INDEX ON "variants" ("value", "group_id");

CREATE UNIQUE INDEX ON "wishlist_items" ("user_id", "product_id");

ALTER TABLE "user_profiles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_profiles" ADD FOREIGN KEY ("default_address_id") REFERENCES "user_addresses" ("id");

ALTER TABLE "wallets" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "wallet_histories" ADD FOREIGN KEY ("wallet_id") REFERENCES "wallets" ("id");

ALTER TABLE "sealabs_pays" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_addresses" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_addresses" ADD FOREIGN KEY ("province_id") REFERENCES "provinces" ("id");

ALTER TABLE "user_addresses" ADD FOREIGN KEY ("city_id") REFERENCES "cities" ("id");

ALTER TABLE "user_addresses" ADD FOREIGN KEY ("district_id") REFERENCES "districts" ("id");

ALTER TABLE "user_addresses" ADD FOREIGN KEY ("subdistrict_id") REFERENCES "subdistricts" ("id");

ALTER TABLE "cities" ADD FOREIGN KEY ("province_id") REFERENCES "provinces" ("id");

ALTER TABLE "districts" ADD FOREIGN KEY ("city_id") REFERENCES "cities" ("id");

ALTER TABLE "subdistricts" ADD FOREIGN KEY ("district_id") REFERENCES "districts" ("id");

ALTER TABLE "shops" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "shops" ADD FOREIGN KEY ("address_id") REFERENCES "user_addresses" ("id");

ALTER TABLE "shop_categories" ADD FOREIGN KEY ("shop_id") REFERENCES "shops" ("id");

ALTER TABLE "shop_category_products" ADD FOREIGN KEY ("shop_category_id") REFERENCES "shop_categories" ("id");

ALTER TABLE "shop_category_products" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "shop_guests" ADD FOREIGN KEY ("shop_id") REFERENCES "shops" ("id");

ALTER TABLE "courier_services" ADD FOREIGN KEY ("courier_id") REFERENCES "couriers" ("id");

ALTER TABLE "shop_couriers" ADD FOREIGN KEY ("shop_id") REFERENCES "shops" ("id");

ALTER TABLE "shop_couriers" ADD FOREIGN KEY ("courier_service_id") REFERENCES "courier_services" ("id");

ALTER TABLE "products" ADD FOREIGN KEY ("shop_id") REFERENCES "shops" ("id");

ALTER TABLE "products" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "product_couriers" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "product_couriers" ADD FOREIGN KEY ("courier_service_id") REFERENCES "courier_services" ("id");

ALTER TABLE "product_bulk_prices" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "product_medias" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "variant_groups" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "variants" ADD FOREIGN KEY ("group_id") REFERENCES "variant_groups" ("id");

ALTER TABLE "product_variants" ADD FOREIGN KEY ("sku_id") REFERENCES "skus" ("id");

ALTER TABLE "product_variants" ADD FOREIGN KEY ("variant") REFERENCES "variants" ("id");

ALTER TABLE "skus" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("invoice_id") REFERENCES "invoice_per_shops" ("id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("address_id") REFERENCES "user_addresses" ("id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("sku_id") REFERENCES "skus" ("id");

ALTER TABLE "transaction_reviews" ADD FOREIGN KEY ("transactions_id") REFERENCES "transactions" ("id");

ALTER TABLE "review_medias" ADD FOREIGN KEY ("review_id") REFERENCES "transaction_reviews" ("id");

ALTER TABLE "invoice_per_shops" ADD FOREIGN KEY ("promotion_id") REFERENCES "promotions" ("id");

ALTER TABLE "invoice_per_shops" ADD FOREIGN KEY ("shop_id") REFERENCES "shops" ("id");

ALTER TABLE "invoice_per_shops" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "invoice_per_shops" ADD FOREIGN KEY ("voucher_id") REFERENCES "user_vouchers" ("id");

ALTER TABLE "invoice_per_shops" ADD FOREIGN KEY ("invoice_id") REFERENCES "invoices" ("id");

ALTER TABLE "invoices" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "invoices" ADD FOREIGN KEY ("voucher_id") REFERENCES "user_vouchers" ("id");

ALTER TABLE "invoices" ADD FOREIGN KEY ("payment_method_id") REFERENCES "payment_methods" ("id");

ALTER TABLE "invoice_status" ADD FOREIGN KEY ("invoice_per_shop_id") REFERENCES "invoice_per_shops" ("id");

ALTER TABLE "shop_vouchers" ADD FOREIGN KEY ("shop_id") REFERENCES "shops" ("id");

ALTER TABLE "marketplace_vouchers" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "marketplace_vouchers" ADD FOREIGN KEY ("payment_method_id") REFERENCES "payment_methods" ("id");

ALTER TABLE "user_vouchers" ADD FOREIGN KEY ("shop_voucher_id") REFERENCES "shop_vouchers" ("id");

ALTER TABLE "user_vouchers" ADD FOREIGN KEY ("marketplace_voucher_id") REFERENCES "marketplace_vouchers" ("id");

ALTER TABLE "categories" ADD FOREIGN KEY ("parent_id") REFERENCES "categories" ("id");

ALTER TABLE "cart_items" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "cart_items" ADD FOREIGN KEY ("sku_id") REFERENCES "skus" ("id");

ALTER TABLE "wishlist_items" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "wishlist_items" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "promotions" ADD FOREIGN KEY ("shop_id") REFERENCES "shops" ("id");

ALTER TABLE "promotion_products" ADD FOREIGN KEY ("sku_id") REFERENCES "skus" ("id");

ALTER TABLE "promotion_products" ADD FOREIGN KEY ("promotion_id") REFERENCES "promotions" ("id");

ALTER TABLE "refund_requests" ADD FOREIGN KEY ("transaction_id") REFERENCES "transactions" ("id");

ALTER TABLE "refund_chats" ADD FOREIGN KEY ("sender_id") REFERENCES "users" ("id");

ALTER TABLE "refund_chats" ADD FOREIGN KEY ("request_id") REFERENCES "refund_requests" ("id");