package code

var (
	MAX_ADDRESS_REACHED                    = "MAX_ADDRESS_REACHED"
	MUST_HAVE_AT_LEAST_ONE_DEFAULT_ADDRESS = "MUST_HAVE_AT_LEAST_ONE_DEFAULT_ADDRESS"
	MUST_HAVE_AT_LEAST_ONE_PICKUP_ADDRESS  = "MUST_HAVE_AT_LEAST_ONE_PICKUP_ADDRESS"
)
