package code

var (
	OK      = "OK"
	CREATED = "CREATED"
	UPDATED = "UPDATED"
	DELETED = "DELETED"

	INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
	BAD_REQUEST = "BAD_REQUEST"
	EMAIL_ALREADY_REGISTERED = "EMAIL_ALREADY_REGISTERED"
)
