package code

var (
	OK      = "OK"
	CREATED = "CREATED"
	UPDATED = "UPDATED"
	DELETED = "DELETED"

	BAD_REQUEST           = "BAD_REQUEST"
	INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
	UNAUTHORIZED          = "UNAUTHORIZED"
)
