package code

const (
	CART_ITEM_MISMATCH                = "CART_ITEM_MISMATCH"
	MINIMUM_SPEND_REQUIREMENT_NOT_MET = "MINIMUM_SPEND_REQUIREMENT_NOT_MET"
	INVOICE_NOT_FOUND                 = "INVOICE_NOT_FOUND"
	INVOICE_NOT_COMPLETED             = "INVOICE_NOT_COMPLETED"
)
