package code

var (
	INVALID_PROMOTION_NAME          = "INVALID_PROMOTION_NAME"
	PROMOTION_NOT_FOUND             = "PROMOTION_NOT_FOUND"
	PROMOTION_FIELDS_CANT_BE_EDITED = "PROMOTION_FIELDS_CANT_BE_EDITED"
	PROMOTION_STATUS_CONFLICT       = "PROMOTION_STATUS_CONFLICT"
)
