package code

var (
	TRANSACTION_REVIEW_ALREADY_EXIST = "TRANSACTION_REVIEW_ALREADY_EXIST"
	TRANSACTION_NOT_FOUND            = "TRANSACTION_NOT_FOUND"
	TRANSACTION_REVIEW_NOT_FOUND     = "TRANSACTION_REVIEW_NOT_FOUND"
)
