package code

var (
<<<<<<< HEAD
	USER_NOT_REGISTERED = "USER_NOT_REGISTERED"
=======
	USER_NOT_REGISTERED      = "USER_NOT_REGISTERED"
	EMAIL_ALREADY_REGISTERED = "EMAIL_ALREADY_REGISTERED"
>>>>>>> e4fd8db74c2d1f5d9ac94cf1de0592b0a77f3219
)
