package code

var (
	USER_NOT_REGISTERED         = "USER_NOT_REGISTERED"
	EMAIL_ALREADY_REGISTERED    = "EMAIL_ALREADY_REGISTERED"
	USERNAME_ALREADY_REGISTERED = "USERNAME_ALREADY_REGISTERED"
	INVALID_PASSWORD_PATTERN    = "INVALID_PASSWORD_PATTERN"
	INVALID_USERNAME_PATTERN    = "INVALID_USERNAME_PATTERN"
	PASSWORD_CONTAIN_EMAIL      = "PASSWORD_CONTAIN_EMAIL"
	PASSWORD_CONTAIN_USERNAME   = "PASSWORD_CONTAIN_USERNAME"
	TOKEN_EXPIRED               = "TOKEN_EXPIRED"
	WRONG_PASSWORD              = "WRONG_PASSWORD"
	SAME_PASSWORD               = "SAME_PASSWORD"
)
