package code

var (
	INVALID_VOUCHER_NAME    = "INVALID_VOUCHER_NAME"
	VOUCHER_NOT_FOUND       = "VOUCHER_NOT_FOUND"
	VOUCHER_STATUS_CONFLICT = "VOUCHER_STATUS_CONFLICT"
	DUPLICATE_VOUCHER_CODE  = "DUPLICATE_VOUCHER_CODE"
	INVALID_DATE_RANGE      = "INVALID_DATE_RANGE"
)
