package code

const (
	WALLET_ALREADY_EXIST  = "WALLET_ALREADY_EXIST"
	WALLET_DOES_NOT_EXIST = "WALLET_DOES_NOT_EXIST"
	INVALID_PIN           = "INVALID_PIN"
	INSUFFICIENT_BALANCE  = "INSUFFICIENT_BALANCE"
)
